"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os.path
from setuptools import setup
from setuptools.extension import Extension

ROOT = os.path.dirname(__file__)

APP = ['mvc/ui/widgets.py']
DATA_FILES = ['mvc/widgets/osx/Resources-Widgets/MainMenu.nib']
OPTIONS = {
    'excludes': ['mvc.widgets.gtk'],
    'includes': ['mvc.widgets.osx.fasttypes'],
    'packages': ['mvc'],
}
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    ext_modules=[
        Extension("mvc.widgets.osx.fasttypes",
                  [os.path.join(ROOT, 'mvc', 'widgets', 'osx', 'fasttypes.c')])]
    )
